// These types match the structure generated by scripts/generate-assets.ts
export interface PostMetadata {
  slug: string;
  title: string;
  date: string;
  dateLabel?: string;
  author: string;
  authorSlug?: string;
  excerpt: string;
  tags: string[];
  coverImage?: string;
  category?: string;
  publishDate?: string;
  draft?: boolean;
  file?: string;
  promotional?: boolean;
  partner?: string;
  callToAction?: string;
}

export interface PostData extends PostMetadata {
  content: string;
}

export interface PageData {
  slug: string;
  title: string;
  content: string;
  draft?: boolean;
  tags: string[];
  file?: string;
  partner?: string;
}

export interface AuthorData {
  slug: string;
  name: string;
  title: string;
  company?: string;
  image?: string;
  shortBio?: string;
  content: string;
  draft?: boolean;
  social?: {
    linkedin?: string;
    twitter?: string;
    github?: string;
    website?: string;
    email?: string;
  };
  skills?: string[];
  file?: string;
}

export interface ThemeItem {
  id: string;
  label: string;
  tag: string;
}

export interface NavItem {
  label?: string;
  type: 'page' | 'tag' | 'blog' | 'menu' | 'model' | 'validate';
  slug?: string;
  subitems?: NavItem[];
}

import { CONFIG } from '../config';

export interface ContentConfig {
  nav: NavItem[];
  themes: ThemeItem[];
}

let fetchedVersion: string | null = null;
let versionPromise: Promise<string> | null = null;

export async function getBuildVersion(): Promise<string> {
  if (fetchedVersion) {
    return fetchedVersion;
  }
  if (versionPromise) {
    return versionPromise;
  }
  versionPromise = (async () => {
    try {
      const data = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/version.json`, true);
      fetchedVersion = data?.version || '1';
      return fetchedVersion;
    } catch (error) {
      console.error('Failed to load version.json, using fallback:', error);
      return '1';
    } finally {
      versionPromise = null;
    }
  })();
  return versionPromise;
}

let cachedContentConfig: ContentConfig | null = null;

export async function getContentConfig(): Promise<ContentConfig> {
  if (cachedContentConfig) {
    return cachedContentConfig;
  }
  try {
    const data = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/content-config.json`);
    cachedContentConfig = {
      nav: data?.nav || [],
      themes: data?.themes || []
    };
    return cachedContentConfig;
  } catch (error) {
    console.error('Error loading content config:', error);
    return { nav: [], themes: [] };
  }
}

export interface TagIndex {
  [tag: string]: {
    posts: string[];
    pages: string[];
  };
}

// Keep track of pending loads to avoid duplicate requests for simultaneous needs
const pendingLoads = new Map<string, Promise<any>>();

async function fetchJSON(url: string, bypassVersionCacheBust = false): Promise<any> {
  let cacheBustUrl = url;
  if (bypassVersionCacheBust) {
    cacheBustUrl = `${url}?cb=${Date.now()}`;
  } else {
    const version = await getBuildVersion();
    cacheBustUrl = `${url}?v=${version}`;
  }

  if (pendingLoads.has(cacheBustUrl)) {
    return pendingLoads.get(cacheBustUrl);
  }

  const promise = (async () => {
    try {
      const response = await fetch(cacheBustUrl);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();
      return data;
    } finally {
      pendingLoads.delete(cacheBustUrl);
    }
  })();

  pendingLoads.set(cacheBustUrl, promise);
  return promise;
}

export async function getAllPostMetadata(): Promise<PostMetadata[]> {
  const posts = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/posts.json`) as PostMetadata[] || [];
  return [...posts]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export async function getPostBySlug(slug: string): Promise<PostData | null> {
  try {
    const data = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/posts/${slug}.json`);
    return data || null;
  } catch (error) {
    console.error(`Error loading post ${slug}:`, error);
    return null;
  }
}

export async function getPageBySlug(slug: string): Promise<PageData | null> {
  try {
    const data = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/pages/${slug}.json`);
    return data || null;
  } catch (error) {
    console.error(`Error loading page ${slug}:`, error);
    return null;
  }
}

export async function getAuthorBySlug(slug: string): Promise<AuthorData | null> {
  try {
    const data = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/authors/${slug}.json`);
    return data || null;
  } catch (error) {
    console.error(`Error loading author ${slug}:`, error);
    return null;
  }
}

export async function getTagIndex(): Promise<TagIndex> {
  try {
    const index = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/tags.json`);
    return index || {};
  } catch (error) {
    console.error('Error loading tag index:', error);
    return {};
  }
}

export async function getPostsByTag(tag: string, offset: number = 0, limit: number = 10): Promise<PostMetadata[]> {
  const normalizedTag = tag.toLowerCase().trim();
  const index = await getTagIndex();
  const entry = index[normalizedTag];
  
  if (!entry || !entry.posts.length) return [];
  
  const allPosts = await getAllPostMetadata();
  const taggedSlugs = new Set(entry.posts);
  
  return allPosts
    .filter(p => taggedSlugs.has(p.slug))
    .slice(offset, offset + limit);
}

export async function getTagPageSlugs(tag: string): Promise<string[]> {
  const normalizedTag = tag.toLowerCase().trim();
  const index = await getTagIndex();
  const entry = index[normalizedTag];
  return entry?.pages || [];
}

export async function getRelatedPostSlugs(currentSlug: string, count: number = 3): Promise<string[]> {
  const allPosts = await getAllPostMetadata();
  const currentPost = allPosts.find(p => p.slug === currentSlug);
  
  if (!currentPost || !currentPost.tags || currentPost.tags.length === 0) return [];
  
  const currentTags = new Set(currentPost.tags.map(t => t.toLowerCase().trim()));
  
  const related = allPosts
    .filter(p => p.slug !== currentSlug)
    .map(p => {
      const commonTags = p.tags.filter(t => currentTags.has(t.toLowerCase().trim())).length;
      return { slug: p.slug, commonTags, date: new Date(p.date).getTime() };
    })
    .filter(item => item.commonTags > 0)
    .sort((a, b) => b.commonTags - a.commonTags || b.date - a.date)
    .slice(0, count)
    .map(item => item.slug);
    
  return related;
}
