// These types match the structure generated by scripts/generate-assets.ts
export interface PostMetadata {
  slug: string;
  title: string;
  date: string;
  author: string;
  authorSlug?: string;
  excerpt: string;
  tags: string[];
  coverImage?: string;
  category?: string;
}

export interface PostData extends PostMetadata {
  content: string;
}

export interface PageData {
  slug: string;
  title: string;
  content: string;
}

export interface AuthorData {
  slug: string;
  name: string;
  title: string;
  company?: string;
  image?: string;
  shortBio?: string;
  content: string;
}

// Global declaration for JSONP content
declare global {
  interface Window {
    CONTENT_POSTS_INDEX: PostMetadata[];
    CONTENT_PAGES_INDEX: PageData[];
    CONTENT_AUTHORS_INDEX: AuthorData[];
    CONTENT_TAGS_INDEX: TagIndex;
  }
}

export interface TagIndex {
  [tag: string]: {
    posts: string[];
    pages: string[];
  };
}

async function loadJSONP(url: string, globalVarName: string): Promise<any> {
  if ((globalThis as any)[globalVarName]) {
    return (globalThis as any)[globalVarName];
  }

  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = url;
    script.async = true;
    script.onload = () => {
      resolve((globalThis as any)[globalVarName]);
    };
    script.onerror = () => {
      reject(new Error(`Failed to load JSONP from ${url}`));
    };
    document.body.appendChild(script);
  });
}

export function getAllPostMetadata(): PostMetadata[] {
  const posts = (globalThis as any).CONTENT_POSTS_INDEX as PostMetadata[] || [];
  return [...posts].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export async function getPostBySlug(slug: string): Promise<PostData | null> {
  const sanitizedSlug = slug.replace(/[^a-zA-Z0-9]/g, '_');
  const globalVarName = `CONTENT_POST_${sanitizedSlug}`;
  
  try {
    const data = await loadJSONP(`/content/posts/${slug}.js`, globalVarName);
    return data || null;
  } catch (error) {
    console.error(`Error loading post ${slug}:`, error);
    return null;
  }
}

export async function getPageBySlug(slug: string): Promise<PageData | null> {
  const sanitizedSlug = slug.replace(/[^a-zA-Z0-9]/g, '_');
  const globalVarName = `CONTENT_PAGE_${sanitizedSlug}`;
  
  try {
    const data = await loadJSONP(`/content/pages/${slug}.js`, globalVarName);
    return data || null;
  } catch (error) {
    console.error(`Error loading page ${slug}:`, error);
    return null;
  }
}

export function getAllAuthors(): AuthorData[] {
  return (globalThis as any).CONTENT_AUTHORS_INDEX as AuthorData[] || [];
}

export async function getAuthorBySlug(slug: string): Promise<AuthorData | null> {
  const sanitizedSlug = slug.replace(/[^a-zA-Z0-9]/g, '_');
  const globalVarName = `CONTENT_AUTHOR_${sanitizedSlug}`;
  
  try {
    const data = await loadJSONP(`/content/authors/${slug}.js`, globalVarName);
    return data || null;
  } catch (error) {
    console.error(`Error loading author ${slug}:`, error);
    return null;
  }
}

export async function getTagIndex(): Promise<TagIndex> {
  if ((globalThis as any).CONTENT_TAGS_INDEX) {
    return (globalThis as any).CONTENT_TAGS_INDEX;
  }
  
  try {
    await loadJSONP('/content/tags.js', 'CONTENT_TAGS_INDEX');
    return (globalThis as any).CONTENT_TAGS_INDEX || {};
  } catch (error) {
    console.error('Error loading tag index:', error);
    return {};
  }
}

export async function getPostsByTag(tag: string, offset: number = 0, limit: number = 10): Promise<PostMetadata[]> {
  const normalizedTag = tag.toLowerCase().trim();
  const index = await getTagIndex();
  const entry = index[normalizedTag];
  
  if (!entry || !entry.posts.length) return [];
  
  const allPosts = getAllPostMetadata();
  const taggedSlugs = new Set(entry.posts);
  
  return allPosts
    .filter(p => taggedSlugs.has(p.slug))
    .slice(offset, offset + limit);
}

export async function getTagPageSlugs(tag: string): Promise<string[]> {
  const normalizedTag = tag.toLowerCase().trim();
  const index = await getTagIndex();
  const entry = index[normalizedTag];
  return entry?.pages || [];
}
