// These types match the structure generated by scripts/generate-assets.ts
export interface PostMetadata {
  slug: string;
  title: string;
  date: string;
  dateLabel?: string;
  author: string;
  authorSlug?: string;
  excerpt: string;
  tags: string[];
  coverImage?: string;
  category?: string;
  publishDate?: string;
}

export interface PostData extends PostMetadata {
  content: string;
}

export interface PageData {
  slug: string;
  title: string;
  content: string;
}

export interface AuthorData {
  slug: string;
  name: string;
  title: string;
  company?: string;
  image?: string;
  shortBio?: string;
  content: string;
  social?: {
    linkedin?: string;
    twitter?: string;
    github?: string;
    website?: string;
    email?: string;
  };
  skills?: string[];
}

import { CONFIG } from '../config';

export interface TagIndex {
  [tag: string]: {
    posts: string[];
    pages: string[];
  };
}

// Keep track of pending loads to avoid duplicate requests for simultaneous needs
const pendingLoads = new Map<string, Promise<any>>();

async function fetchJSON(url: string): Promise<any> {
  const dateStr = new Date().toISOString().split('T')[0];
  const cacheBustUrl = `${url}?t=${dateStr}`;

  if (pendingLoads.has(cacheBustUrl)) {
    return pendingLoads.get(cacheBustUrl);
  }

  const promise = (async () => {
    try {
      const response = await fetch(cacheBustUrl);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();
      return data;
    } finally {
      pendingLoads.delete(cacheBustUrl);
    }
  })();

  pendingLoads.set(cacheBustUrl, promise);
  return promise;
}

export async function getAllPostMetadata(): Promise<PostMetadata[]> {
  const posts = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/posts.json`) as PostMetadata[] || [];
  return [...posts]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export async function getPostBySlug(slug: string): Promise<PostData | null> {
  try {
    const data = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/posts/${slug}.json`);
    return data || null;
  } catch (error) {
    console.error(`Error loading post ${slug}:`, error);
    return null;
  }
}

export async function getPageBySlug(slug: string): Promise<PageData | null> {
  try {
    const data = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/pages/${slug}.json`);
    return data || null;
  } catch (error) {
    console.error(`Error loading page ${slug}:`, error);
    return null;
  }
}

export async function getAllAuthors(): Promise<AuthorData[]> {
  return await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/authors.json`) as AuthorData[] || [];
}

export async function getAuthorBySlug(slug: string): Promise<AuthorData | null> {
  try {
    const data = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/authors/${slug}.json`);
    return data || null;
  } catch (error) {
    console.error(`Error loading author ${slug}:`, error);
    return null;
  }
}

export async function getTagIndex(): Promise<TagIndex> {
  try {
    const index = await fetchJSON(`${CONFIG.basePath.replace(/\/$/, '')}/content/tags.json`);
    return index || {};
  } catch (error) {
    console.error('Error loading tag index:', error);
    return {};
  }
}

export async function getPostsByTag(tag: string, offset: number = 0, limit: number = 10): Promise<PostMetadata[]> {
  const normalizedTag = tag.toLowerCase().trim();
  const index = await getTagIndex();
  const entry = index[normalizedTag];
  
  if (!entry || !entry.posts.length) return [];
  
  const allPosts = await getAllPostMetadata();
  const taggedSlugs = new Set(entry.posts);
  
  return allPosts
    .filter(p => taggedSlugs.has(p.slug))
    .slice(offset, offset + limit);
}

export async function getTagPageSlugs(tag: string): Promise<string[]> {
  const normalizedTag = tag.toLowerCase().trim();
  const index = await getTagIndex();
  const entry = index[normalizedTag];
  return entry?.pages || [];
}
